# Generated by Django 4.2.9 on 2024-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
