# Generated by Django 4.2.9 on 2024-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
