# Generated by Django 4.2.7 on 2023-12-20 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_access_token_remove_user_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_balance",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
