name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
            pipx install poetry
#            curl -sSL https://install.python-poetry.org | python3 -
            poetry install

      - name: Lint and Format
        run: |
          flake8
          mypy
          isort
          black
          pylint