# Generated by Django 4.2.9 on 2024-01-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=3, max_digits=30)),
                (
                    "transaction_price",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("currency", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("Покупка", "Покупка"), ("Продажа", "Продажа")],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategories",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("криптовалюта", "криптовалюта"),
                            ("акции", "акции"),
                            ("фьючерсы", "фьючерсы"),
                            ("облигации", "облигации"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock_market.productcategories",
                    ),
                ),
            ],
            bases=("common.basemodel",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(editable=False, primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "name",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock_market.productcategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
