# Generated by Django 4.2.9 on 2024-01-26 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
    ]
