# Generated by Django 4.2.9 on 2024-01-26 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0002_remove_order_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
    ]
