# Generated by Django 4.2.9 on 2024-01-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0004_remove_order_user_id_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product_id",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock_market.product",
            ),
            preserve_default=False,
        ),
    ]
