# Generated by Django 4.2.9 on 2024-01-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0006_alter_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stock_market.product"
            ),
        ),
    ]
