# Generated by Django 4.2.9 on 2024-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0007_alter_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(max_length=100),
        ),
    ]
