# Generated by Django 4.2.9 on 2024-01-26 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0008_alter_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="product_id",
        ),
    ]
