# Generated by Django 4.2.9 on 2024-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0008_alter_product_symbol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="highPrice",
            new_name="high_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="lastPrice",
            new_name="last_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="lowPrice",
            new_name="low_price",
        ),
    ]
