# Generated by Django 4.2.10 on 2024-03-03 19:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0009_rename_highprice_product_high_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4af5bbfb-79ed-4896-b671-e14631a565fe"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
