# Generated by Django 4.2.10 on 2024-03-13 18:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0009_rename_highprice_product_high_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
