# Generated by Django 4.2.10 on 2024-03-14 16:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0010_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Успешно", "Успешно"),
                    ("Отменено", "Отменено"),
                    ("В_процессе", "В_процессе"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("Покупка", "Покупка"),
                    ("Продажа", "Продажа"),
                    ("Авто_Продажа", "Авто_Продажа"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9933deb8-be65-4746-8669-3827e2bdd5db"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
