# Generated by Django 4.2.10 on 2024-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stock_market",
            "0010_order_currency_price_order_status_alter_order_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
