# Generated by Django 4.2.10 on 2024-03-15 17:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0011_order_status_alter_order_type_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("Покупка", "Покупка"),
                    ("Продажа", "Продажа"),
                    ("Авто_Продажа", "Авто_Продажа"),
                    ("Авто_Пoкупка", "Авто_Покупка"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b72a264c-22ed-4f03-9e74-c12736467986"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
