# Generated by Django 4.2.7 on 2023-11-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("криптовалюта", "CRYPTOCURRENCY"),
                            ("акции", "STOCK"),
                            ("фьючерсы", "FUTURES"),
                            ("облигации", "BONDS"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.productcategories",
                    ),
                ),
            ],
        ),
    ]
